### ISSUE TITLE
future plans for the project

### ISSUE THREAD

**Issue by SingingBush** [shove70/database#1]
Hi, I currently work on [ddbc](https://github.com/buggins/ddbc/) which supports MySQL (via [mysql-native](https://github.com/mysql-d/mysql-native)), PostgreSQL (via derelict-pq), SQLite and SQL Server (via `etc.c.odbc`). I'd be interested to know if this project will eventually support other databases. 

I like using sqlite for testing locally and mysql/postgressql for personal projects but absolutely need MS-SQL / Oracle support to be able to use D for any workplace projects.

With `etc.c.odbc` now [being removed in feb 2022](https://forum.dlang.org/thread/rspvigghtqnerlbszctx@forum.dlang.org), I need to find an alternative and I don't really have the time to overhaul ddbc by that date. Is odbc support something you plan to do?

**Comment by shove70** [comment]
Hello, I haven't thought about this plan yet. At least I don't have time to start it in a short time. In fact, I hope I can start it too. I'm so sorry.
